name: Build and Push Docker Image with Security Checks

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 713881828888.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: chess-game

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Buildx
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Step 6: Pull Docker Image for Scanning
      - name: Pull Docker Image
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Step 7: Run Trivy for Vulnerability Scanning
      - name: Run Trivy for Vulnerability Scanning
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
          ./bin/trivy image --severity HIGH,CRITICAL $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Step 8: Notify Discord on Success
      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"✅ Docker image built and pushed successfully!\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Step 9: Notify Discord on Failure
      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"❌ Docker image build or push failed. Please check the logs for details.\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
