name: Terraform Deployment Workflow

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Terraform
      - name: Install Terraform
        run: |
          mkdir -p /tmp/terraform_install
          wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip -O /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /tmp/terraform_install
          sudo mv /tmp/terraform_install/terraform /usr/local/bin/
        shell: bash

      # Step 3: Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      # Step 5: Check Confirmation
      - name: Check Confirmation
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Confirmation not given. Exiting..."
            exit 1
          fi

      # Step 6: Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 7: Notify Discord on Success
      - name: Notify Discord Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"✅ Terraform deployment completed successfully!\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Step 8: Notify Discord on Failure
      - name: Notify Discord Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"❌ Terraform deployment failed! Please check the logs.\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
